// ۱۰۰ عکس نمونه — تولید خودکار
const PHOTOS=[
{f:'photos/p001.jpg',t:'غروب رؤیایی 1',premium:false},
{f:'photos/p002.jpg',t:'اقیانوس آرام 1',premium:false},
{f:'photos/p003.jpg',t:'بهار دل‌انگیز 1',premium:false},
{f:'photos/p004.jpg',t:'شب پرستاره 1',premium:false},
{f:'photos/p005.jpg',t:'شب یلدایی 1',premium:false},
{f:'photos/p006.jpg',t:'عاشقانه 1',premium:false},
{f:'photos/p007.jpg',t:'طلایی لوکس 1',premium:false},
{f:'photos/p008.jpg',t:'نعنایی خنک 1',premium:false},
{f:'photos/p009.jpg',t:'کهکشان بنفش 1',premium:false},
{f:'photos/p010.jpg',t:'هلویی لطیف 1',premium:false},
{f:'photos/p011.jpg',t:'غروب رؤیایی 2',premium:false},
{f:'photos/p012.jpg',t:'اقیانوس آرام 2',premium:false},
{f:'photos/p013.jpg',t:'بهار دل‌انگیز 2',premium:false},
{f:'photos/p014.jpg',t:'شب پرستاره 2',premium:false},
{f:'photos/p015.jpg',t:'شب یلدایی 2',premium:false},
{f:'photos/p016.jpg',t:'عاشقانه 2',premium:false},
{f:'photos/p017.jpg',t:'طلایی لوکس 2',premium:false},
{f:'photos/p018.jpg',t:'نعنایی خنک 2',premium:false},
{f:'photos/p019.jpg',t:'کهکشان بنفش 2',premium:false},
{f:'photos/p020.jpg',t:'هلویی لطیف 2',premium:false},
{f:'photos/p021.jpg',t:'غروب رؤیایی 3',premium:false},
{f:'photos/p022.jpg',t:'اقیانوس آرام 3',premium:false},
{f:'photos/p023.jpg',t:'بهار دل‌انگیز 3',premium:false},
{f:'photos/p024.jpg',t:'شب پرستاره 3',premium:false},
{f:'photos/p025.jpg',t:'شب یلدایی 3',premium:false},
{f:'photos/p026.jpg',t:'عاشقانه 3',premium:false},
{f:'photos/p027.jpg',t:'طلایی لوکس 3',premium:false},
{f:'photos/p028.jpg',t:'نعنایی خنک 3',premium:false},
{f:'photos/p029.jpg',t:'کهکشان بنفش 3',premium:false},
{f:'photos/p030.jpg',t:'هلویی لطیف 3',premium:false},
{f:'photos/p031.jpg',t:'غروب رؤیایی 4',premium:false},
{f:'photos/p032.jpg',t:'اقیانوس آرام 4',premium:false},
{f:'photos/p033.jpg',t:'بهار دل‌انگیز 4',premium:false},
{f:'photos/p034.jpg',t:'شب پرستاره 4',premium:false},
{f:'photos/p035.jpg',t:'شب یلدایی 4',premium:false},
{f:'photos/p036.jpg',t:'عاشقانه 4',premium:false},
{f:'photos/p037.jpg',t:'طلایی لوکس 4',premium:false},
{f:'photos/p038.jpg',t:'نعنایی خنک 4',premium:false},
{f:'photos/p039.jpg',t:'کهکشان بنفش 4',premium:false},
{f:'photos/p040.jpg',t:'هلویی لطیف 4',premium:false},
{f:'photos/p041.jpg',t:'غروب رؤیایی 5',premium:false},
{f:'photos/p042.jpg',t:'اقیانوس آرام 5',premium:false},
{f:'photos/p043.jpg',t:'بهار دل‌انگیز 5',premium:false},
{f:'photos/p044.jpg',t:'شب پرستاره 5',premium:false},
{f:'photos/p045.jpg',t:'شب یلدایی 5',premium:false},
{f:'photos/p046.jpg',t:'عاشقانه 5',premium:false},
{f:'photos/p047.jpg',t:'طلایی لوکس 5',premium:false},
{f:'photos/p048.jpg',t:'نعنایی خنک 5',premium:false},
{f:'photos/p049.jpg',t:'کهکشان بنفش 5',premium:false},
{f:'photos/p050.jpg',t:'هلویی لطیف 5',premium:false},
{f:'photos/p051.jpg',t:'غروب رؤیایی 6',premium:false},
{f:'photos/p052.jpg',t:'اقیانوس آرام 6',premium:false},
{f:'photos/p053.jpg',t:'بهار دل‌انگیز 6',premium:false},
{f:'photos/p054.jpg',t:'شب پرستاره 6',premium:false},
{f:'photos/p055.jpg',t:'شب یلدایی 6',premium:false},
{f:'photos/p056.jpg',t:'عاشقانه 6',premium:false},
{f:'photos/p057.jpg',t:'طلایی لوکس 6',premium:false},
{f:'photos/p058.jpg',t:'نعنایی خنک 6',premium:false},
{f:'photos/p059.jpg',t:'کهکشان بنفش 6',premium:false},
{f:'photos/p060.jpg',t:'هلویی لطیف 6',premium:false},
{f:'photos/p061.jpg',t:'غروب رؤیایی 7',premium:false},
{f:'photos/p062.jpg',t:'اقیانوس آرام 7',premium:false},
{f:'photos/p063.jpg',t:'بهار دل‌انگیز 7',premium:false},
{f:'photos/p064.jpg',t:'شب پرستاره 7',premium:false},
{f:'photos/p065.jpg',t:'شب یلدایی 7',premium:false},
{f:'photos/p066.jpg',t:'عاشقانه 7',premium:false},
{f:'photos/p067.jpg',t:'طلایی لوکس 7',premium:false},
{f:'photos/p068.jpg',t:'نعنایی خنک 7',premium:false},
{f:'photos/p069.jpg',t:'کهکشان بنفش 7',premium:false},
{f:'photos/p070.jpg',t:'هلویی لطیف 7',premium:false},
{f:'photos/p071.jpg',t:'غروب رؤیایی 8',premium:false},
{f:'photos/p072.jpg',t:'اقیانوس آرام 8',premium:false},
{f:'photos/p073.jpg',t:'بهار دل‌انگیز 8',premium:false},
{f:'photos/p074.jpg',t:'شب پرستاره 8',premium:false},
{f:'photos/p075.jpg',t:'شب یلدایی 8',premium:false},
{f:'photos/p076.jpg',t:'عاشقانه 8',premium:true},
{f:'photos/p077.jpg',t:'طلایی لوکس 8',premium:true},
{f:'photos/p078.jpg',t:'نعنایی خنک 8',premium:true},
{f:'photos/p079.jpg',t:'کهکشان بنفش 8',premium:true},
{f:'photos/p080.jpg',t:'هلویی لطیف 8',premium:true},
{f:'photos/p081.jpg',t:'غروب رؤیایی 9',premium:true},
{f:'photos/p082.jpg',t:'اقیانوس آرام 9',premium:true},
{f:'photos/p083.jpg',t:'بهار دل‌انگیز 9',premium:true},
{f:'photos/p084.jpg',t:'شب پرستاره 9',premium:true},
{f:'photos/p085.jpg',t:'شب یلدایی 9',premium:true},
{f:'photos/p086.jpg',t:'عاشقانه 9',premium:true},
{f:'photos/p087.jpg',t:'طلایی لوکس 9',premium:true},
{f:'photos/p088.jpg',t:'نعنایی خنک 9',premium:true},
{f:'photos/p089.jpg',t:'کهکشان بنفش 9',premium:true},
{f:'photos/p090.jpg',t:'هلویی لطیف 9',premium:true},
{f:'photos/p091.jpg',t:'غروب رؤیایی 10',premium:true},
{f:'photos/p092.jpg',t:'اقیانوس آرام 10',premium:true},
{f:'photos/p093.jpg',t:'بهار دل‌انگیز 10',premium:true},
{f:'photos/p094.jpg',t:'شب پرستاره 10',premium:true},
{f:'photos/p095.jpg',t:'شب یلدایی 10',premium:true},
{f:'photos/p096.jpg',t:'عاشقانه 10',premium:true},
{f:'photos/p097.jpg',t:'طلایی لوکس 10',premium:true},
{f:'photos/p098.jpg',t:'نعنایی خنک 10',premium:true},
{f:'photos/p099.jpg',t:'کهکشان بنفش 10',premium:true},
{f:'photos/p100.jpg',t:'هلویی لطیف 10',premium:true},
];
