// ۱۰۰ نمونه‌کارت آماده — تولید خودکار
const SAMPLES=[
{o:'birthday',t:'تولدت مبارک عزیزم! 🎂',m:'امروز، روز توست! بدرخش، بخند و بهترین‌ها را زندگی کن.',s:'دوستدارت 🌸',ph:'photos/p008.jpg',mode:'bg',st:['🎂','🎁'],premium:false},
{o:'birthday',t:'یک سال درخشان‌تر شدی ✨',m:'یک سال قشنگ‌تر، باتجربه‌تر و دوست‌داشتنی‌تر شدی!',s:'از طرف خانواده ❤️',ph:'photos/p015.jpg',mode:'frame',st:['🎈','✨'],premium:false},
{o:'birthday',t:'امروز روز توئه! 🎉',m:'آرزو می‌کنم امسال همه آرزوهایت برآورده شود.',s:'با بهترین آرزوها ✨',ph:'photos/p022.jpg',mode:'bg',st:['🎁','⭐'],premium:false},
{o:'birthday',t:'شمع‌ها را فوت کن! 🎂',m:'شمع‌های کیکت کم‌اند برای شمردن خوبی‌هایت!',s:'ارادتمند شما 🤗',ph:'photos/p029.jpg',mode:'frame',st:['✨','🌸'],premium:true},
{o:'birthday',t:'بهترین روز سال رسید 🎈',m:'تو هدیه خدا به دنیایی؛ تولدت مبارک!',s:'همیشه به یادت 🌟',ph:'photos/p036.jpg',mode:'bg',st:['⭐','🎉'],premium:false},
{o:'birthday',t:'تولدت مبارک گل من 🌸',m:'بخند رفیق! امروز مال توئه و فردا هم همین‌طور.',s:'قربانت ❤️',ph:'photos/p043.jpg',mode:'frame',st:['🌸','🎂'],premium:false},
{o:'birthday',t:'سالت پر از معجزه باد ⭐',m:'سفیدبخت و سبزاقبال باشی، همیشه!',s:'با عشق 💜',ph:'photos/p050.jpg',mode:'bg',st:['🎉','🎈'],premium:false},
{o:'nowruz',t:'نوروز پیروز! 🌸',m:'سال نو، دل نو، آرزوهای نو! هفت‌سین دلت همیشه پر باشد.',s:'دوستدارت 🌸',ph:'photos/p057.jpg',mode:'frame',st:['🌸','🍎'],premium:true},
{o:'nowruz',t:'سال نو مبارک! 🌷',m:'بهار طبیعت بر تو و خانواده‌ات مبارک؛ سالی پر از سلامتی!',s:'از طرف خانواده ❤️',ph:'photos/p064.jpg',mode:'bg',st:['🌷','🐟'],premium:false},
{o:'nowruz',t:'عیدت مبارک! 🌿',m:'سفره دلت همیشه پر از عشق و لبخند؛ عیدت مبارک.',s:'با بهترین آرزوها ✨',ph:'photos/p071.jpg',mode:'frame',st:['🍎','🪞'],premium:false},
{o:'nowruz',t:'بهار آمد… 🌸',m:'سبزه بختت همیشه سبز و سکه رزقت همیشه پر!',s:'ارادتمند شما 🤗',ph:'photos/p078.jpg',mode:'bg',st:['🐟','✨'],premium:false},
{o:'nowruz',t:'هفت‌سینت آباد! 🍎',m:'بوی بهار، بوی تازگی؛ سالت سرشار از موفقیت.',s:'همیشه به یادت 🌟',ph:'photos/p085.jpg',mode:'frame',st:['🪞','🌿'],premium:true},
{o:'nowruz',t:'سال نو، دل نو ✨',m:'سیب سرخی بختت، سمنوی شیرین زندگی‌ات!',s:'قربانت ❤️',ph:'photos/p092.jpg',mode:'bg',st:['✨','🌸'],premium:false},
{o:'nowruz',t:'نوروزتان خجسته 🌷',m:'نوروز، جشن نو شدن است؛ تو هم نو شو و بدرخش!',s:'با عشق 💜',ph:'photos/p099.jpg',mode:'frame',st:['🌿','🌷'],premium:false},
{o:'yalda',t:'یلدات مبارک! 🍉',m:'بلندترین شب سال، کوتاه‌ترین غم‌هایت باشد.',s:'دوستدارت 🌸',ph:'photos/p006.jpg',mode:'bg',st:['🍉','🌙'],premium:false},
{o:'yalda',t:'شب چله مبارک ❤️',m:'انار دلت همیشه دانه‌دانه شادی؛ یلدا مبارک!',s:'از طرف خانواده ❤️',ph:'photos/p013.jpg',mode:'frame',st:['❤️','✨'],premium:true},
{o:'yalda',t:'بلندترین شب، کوتاه‌ترین غم 🍉',m:'در این شب بلند، برایت آرزوهای بلند دارم.',s:'با بهترین آرزوها ✨',ph:'photos/p020.jpg',mode:'bg',st:['🌙','🕯️'],premium:false},
{o:'yalda',t:'انار دلت پر دانه باد ✨',m:'حافظ بخوان و فال نیک بزن؛ آینده‌ات روشن است!',s:'ارادتمند شما 🤗',ph:'photos/p027.jpg',mode:'frame',st:['✨','📖'],premium:false},
{o:'yalda',t:'یلدا مبارک رفیق! 🍉',m:'دور هم جمع شوید و گرمای محبت را بچشید.',s:'همیشه به یادت 🌟',ph:'photos/p034.jpg',mode:'bg',st:['🕯️','⭐'],premium:false},
{o:'yalda',t:'شبت یلدایی باد 🌙',m:'یلدا یعنی امید؛ یعنی بعد از بلندترین شب، روز می‌آید.',s:'قربانت ❤️',ph:'photos/p041.jpg',mode:'frame',st:['📖','🍉'],premium:true},
{o:'yalda',t:'هندوانه‌ات شیرین! 🍉',m:'آجیل خنده‌هایت همیشه تازه باد!',s:'با عشق 💜',ph:'photos/p048.jpg',mode:'bg',st:['⭐','❤️'],premium:false},
{o:'valentine',t:'دوستت دارم! ❤️',m:'تو قشنگ‌ترین اتفاق زندگی منی؛ روز عشق مبارک!',s:'دوستدارت 🌸',ph:'photos/p055.jpg',mode:'frame',st:['❤️','💖'],premium:false},
{o:'valentine',t:'روز عشق مبارک 💕',m:'هر روز با تو، روز عشق است؛ دوستت دارم.',s:'از طرف خانواده ❤️',ph:'photos/p062.jpg',mode:'bg',st:['💕','🌹'],premium:false},
{o:'valentine',t:'تو قلبمی! ❤️',m:'قلبم پیش توئه، مواظبش باش!',s:'با بهترین آرزوها ✨',ph:'photos/p069.jpg',mode:'frame',st:['💖','💘'],premium:true},
{o:'valentine',t:'عشق من! 💖',m:'عشق یعنی تو… یعنی همین لبخندت.',s:'ارادتمند شما 🤗',ph:'photos/p076.jpg',mode:'bg',st:['🌹','💐'],premium:false},
{o:'valentine',t:'سپندارمذگان مبارک ❤️',m:'در روز عشق ایران باستان، عشقم را به تو تقدیم می‌کنم.',s:'همیشه به یادت 🌟',ph:'photos/p083.jpg',mode:'frame',st:['💘','😘'],premium:false},
{o:'valentine',t:'تو بهترینی! 💕',m:'تو دلیل لبخند هر روز منی.',s:'قربانت ❤️',ph:'photos/p090.jpg',mode:'bg',st:['💐','❤️'],premium:false},
{o:'valentine',t:'جان دلم! 💘',m:'کاش می‌توانستم تمام ستاره‌ها را برایت بچینم.',s:'با عشق 💜',ph:'photos/p097.jpg',mode:'frame',st:['😘','💕'],premium:true},
{o:'wedding',t:'پیوندتان مبارک! 💍',m:'آرزوی خوشبختی ابدی برای عروس و داماد عزیز!',s:'دوستدارت 🌸',ph:'photos/p004.jpg',mode:'bg',st:['💍','🎉'],premium:false},
{o:'wedding',t:'عروسی‌تان مبارک 🎉',m:'به پای هم جوان بمانید و پیر شوید.',s:'از طرف خانواده ❤️',ph:'photos/p011.jpg',mode:'frame',st:['🕊️','❤️'],premium:false},
{o:'wedding',t:'خوشبخت شوید! 🕊️',m:'خانه‌تان همیشه گرم از عشق و محبت.',s:'با بهترین آرزوها ✨',ph:'photos/p018.jpg',mode:'bg',st:['🎉','💐'],premium:false},
{o:'wedding',t:'به پای هم پیر شوید 💕',m:'این آغاز قشنگ‌ترین فصل زندگی‌تان است.',s:'ارادتمند شما 🤗',ph:'photos/p025.jpg',mode:'frame',st:['❤️','✨'],premium:true},
{o:'wedding',t:'آغاز زیبا مبارک 💍',m:'لبخند امروزتان همیشه بر لب‌هایتان.',s:'همیشه به یادت 🌟',ph:'photos/p032.jpg',mode:'bg',st:['💐','🎊'],premium:false},
{o:'wedding',t:'عشقتان ابدی! ❤️',m:'عشقی که امروز جشنش گرفتید، ابدی باد.',s:'قربانت ❤️',ph:'photos/p039.jpg',mode:'frame',st:['✨','💍'],premium:false},
{o:'wedding',t:'جشن وصلتان مبارک 🎊',m:'قدم‌تان به خانه بخت، پر از خیر و برکت!',s:'با عشق 💜',ph:'photos/p046.jpg',mode:'bg',st:['🎊','🕊️'],premium:false},
{o:'mother',t:'روزت مبارک مامان! 🤱',m:'بهشت زیر پای توست؛ ممنون که هستی، فرشته زمینی من!',s:'دوستدارت 🌸',ph:'photos/p053.jpg',mode:'frame',st:['🤱','❤️'],premium:true},
{o:'mother',t:'ممنون که هستی 🌹',m:'هر چه دارم از دعای توست؛ روزت مبارک.',s:'از طرف خانواده ❤️',ph:'photos/p060.jpg',mode:'bg',st:['🌹','🌸'],premium:false},
{o:'mother',t:'بهشت زیر پای توست 🤱',m:'دستان پرمهرت، گرم‌ترین آغوش دنیاست.',s:'با بهترین آرزوها ✨',ph:'photos/p067.jpg',mode:'frame',st:['❤️','💕'],premium:false},
{o:'mother',t:'فرشته زمینی من! ❤️',m:'مامان! تو قهرمان بی‌ادعای زندگی منی.',s:'ارادتمند شما 🤗',ph:'photos/p074.jpg',mode:'bg',st:['🌸','✨'],premium:false},
{o:'mother',t:'مامان قشنگم! 🌸',m:'خستگی‌هایت را هیچ‌کس ندید؛ ممنونم.',s:'همیشه به یادت 🌟',ph:'photos/p081.jpg',mode:'frame',st:['💕','🦋'],premium:true},
{o:'mother',t:'دوستت دارم مامان 💕',m:'عشق اول و آخرم، روزت مبارک!',s:'قربانت ❤️',ph:'photos/p088.jpg',mode:'bg',st:['✨','🤱'],premium:false},
{o:'mother',t:'سایه‌ات مستدام 🤱',m:'تو بهترینی؛ امروز روز تجلیل از توست.',s:'با عشق 💜',ph:'photos/p095.jpg',mode:'frame',st:['🦋','🌹'],premium:false},
{o:'father',t:'روزت مبارک بابا! 👨‍👧',m:'کوه پشت و پناه من! سایه‌ات مستدام.',s:'دوستدارت 🌸',ph:'photos/p002.jpg',mode:'bg',st:['👨‍👧','💪'],premium:false},
{o:'father',t:'کوه من! 💙',m:'سکوتت پر از حرف بود؛ ممنون برای همه‌چیز.',s:'از طرف خانواده ❤️',ph:'photos/p009.jpg',mode:'frame',st:['💙','⭐'],premium:true},
{o:'father',t:'سایه‌ات مستدام 👨‍👧',m:'تو اولین قهرمانی بودی که شناختم.',s:'با بهترین آرزوها ✨',ph:'photos/p016.jpg',mode:'bg',st:['💪','🤗'],premium:false},
{o:'father',t:'قهرمان من! 💪',m:'دستان پینه‌بسته‌ات، سند افتخار من است.',s:'ارادتمند شما 🤗',ph:'photos/p023.jpg',mode:'frame',st:['⭐','👔'],premium:false},
{o:'father',t:'بابای بهترین! ⭐',m:'بابا! امنیت یعنی بودن تو.',s:'همیشه به یادت 🌟',ph:'photos/p030.jpg',mode:'bg',st:['🤗','✨'],premium:false},
{o:'father',t:'تکیه‌گاهم! 🤗',m:'هر موفقیتم را مدیون زحمت‌های توام.',s:'قربانت ❤️',ph:'photos/p037.jpg',mode:'frame',st:['👔','👨‍👧'],premium:true},
{o:'father',t:'ممنون بابا! 🙏',m:'روز پدر بر بهترین پدر دنیا مبارک!',s:'با عشق 💜',ph:'photos/p044.jpg',mode:'bg',st:['✨','💙'],premium:false},
{o:'teacher',t:'سپاس معلم عزیزم! 📚',m:'الفبای زندگی را از تو آموختم؛ روزت مبارک!',s:'دوستدارت 🌸',ph:'photos/p051.jpg',mode:'frame',st:['📚','🌟'],premium:false},
{o:'teacher',t:'روزت مبارک استاد ✏️',m:'تو چراغ راه هزاران دانش‌آموزی؛ سپاس.',s:'از طرف خانواده ❤️',ph:'photos/p058.jpg',mode:'bg',st:['✏️','📖'],premium:false},
{o:'teacher',t:'ممنون آموزگار! 🌟',m:'صبوری‌ات را هیچ‌وقت فراموش نمی‌کنم.',s:'با بهترین آرزوها ✨',ph:'photos/p065.jpg',mode:'frame',st:['🌟','💡'],premium:true},
{o:'teacher',t:'الفبای زندگی… 📚',m:'هر موفقیتی دارم، ریشه در کلاس تو دارد.',s:'ارادتمند شما 🤗',ph:'photos/p072.jpg',mode:'bg',st:['📖','🍎'],premium:false},
{o:'teacher',t:'قدر دانم! 🙏',m:'معلمی شغل نیست، عشق است؛ و تو عاشقی.',s:'همیشه به یادت 🌟',ph:'photos/p079.jpg',mode:'frame',st:['💡','🎓'],premium:false},
{o:'teacher',t:'استاد گرامی! 📖',m:'به احترامت می‌ایستم، استاد!',s:'قربانت ❤️',ph:'photos/p086.jpg',mode:'bg',st:['🍎','📚'],premium:false},
{o:'teacher',t:'چراغ راهم! 💡',m:'خدا قوت، معلم دلسوز!',s:'با عشق 💜',ph:'photos/p093.jpg',mode:'frame',st:['🎓','✏️'],premium:true},
{o:'grad',t:'فارغ‌التحصیلی مبارک! 🎓',m:'این تازه اول راه است؛ به سوی قله‌ها!',s:'دوستدارت 🌸',ph:'photos/p100.jpg',mode:'bg',st:['🎓','⭐'],premium:false},
{o:'grad',t:'آفرین قهرمان! 🚀',m:'شب‌بیداری‌هایت نتیجه داد؛ آفرین!',s:'از طرف خانواده ❤️',ph:'photos/p007.jpg',mode:'frame',st:['🚀','🎉'],premium:false},
{o:'grad',t:'قله بعدی! 🎓',m:'مدرکت مبارک؛ حالا دنیا منتظر توست.',s:'با بهترین آرزوها ✨',ph:'photos/p014.jpg',mode:'bg',st:['⭐','📜'],premium:false},
{o:'grad',t:'تو کردی! ⭐',m:'تو ثابت کردی خواستن، توانستن است.',s:'ارادتمند شما 🤗',ph:'photos/p021.jpg',mode:'frame',st:['🎉','✨'],premium:true},
{o:'grad',t:'تبریک فارغ‌التحصیل! 🎉',m:'آینده از آنِ توست؛ محکم قدم بردار.',s:'همیشه به یادت 🌟',ph:'photos/p028.jpg',mode:'bg',st:['📜','🌟'],premium:false},
{o:'grad',t:'به سوی آینده! 🚀',m:'خانواده‌ات به تو افتخار می‌کنند.',s:'قربانت ❤️',ph:'photos/p035.jpg',mode:'frame',st:['✨','🎓'],premium:false},
{o:'grad',t:'موفق باشی همیشه! 🌟',m:'جشن بگیر! امروز روز توست.',s:'با عشق 💜',ph:'photos/p042.jpg',mode:'bg',st:['🌟','🚀'],premium:false},
{o:'baby',t:'قدم نو رسیده مبارک! 👶',m:'فرشته کوچولو به جمع‌مان خوش آمد!',s:'دوستدارت 🌸',ph:'photos/p049.jpg',mode:'frame',st:['👶','🧸'],premium:true},
{o:'baby',t:'فرشته آمد! 🍼',m:'قدمش پرخیر و برکت برای خانواده.',s:'از طرف خانواده ❤️',ph:'photos/p056.jpg',mode:'bg',st:['🍼','🌸'],premium:false},
{o:'baby',t:'نی‌نی مبارک! 👶',m:'خنده‌هایش خانه‌تان را پر از شادی کند.',s:'با بهترین آرزوها ✨',ph:'photos/p063.jpg',mode:'frame',st:['🧸','💕'],premium:false},
{o:'baby',t:'خوش آمدی کوچولو 🌸',m:'خدا حفظش کند و عاقبت‌به‌خیر شود.',s:'ارادتمند شما 🤗',ph:'photos/p070.jpg',mode:'bg',st:['🌸','✨'],premium:false},
{o:'baby',t:'چشم‌روشنی! 👶',m:'چه حس قشنگی است عمو/خاله/دایی شدن!',s:'همیشه به یادت 🌟',ph:'photos/p077.jpg',mode:'frame',st:['💕','🐣'],premium:true},
{o:'baby',t:'خدا حفظش کنه 🤲',m:'نوزادتان سالم و صالح بزرگ شود.',s:'قربانت ❤️',ph:'photos/p084.jpg',mode:'bg',st:['✨','👶'],premium:false},
{o:'baby',t:'مبارک باشه! 🧸',m:'این کوچولو، بزرگ‌ترین شادی زندگی‌تان است.',s:'با عشق 💜',ph:'photos/p091.jpg',mode:'frame',st:['🐣','🍼'],premium:false},
{o:'eid',t:'عید مبارک! 🌙',m:'طاعات و عباداتت قبول درگاه حق!',s:'دوستدارت 🌸',ph:'photos/p098.jpg',mode:'bg',st:['🌙','✨'],premium:false},
{o:'eid',t:'طاعاتت قبول 🕌',m:'عید سعید بر تو و خانواده‌ات مبارک.',s:'از طرف خانواده ❤️',ph:'photos/p005.jpg',mode:'frame',st:['🕌','🤲'],premium:true},
{o:'eid',t:'عید سعید مبارک ✨',m:'بعد از یک ماه بندگی، جشن بگیر! عیدت مبارک.',s:'با بهترین آرزوها ✨',ph:'photos/p012.jpg',mode:'bg',st:['✨','⭐'],premium:false},
{o:'eid',t:'فطر/قربان مبارک 🌙',m:'خدا زیارت و قربانی‌ات را قبول کند.',s:'ارادتمند شما 🤗',ph:'photos/p019.jpg',mode:'frame',st:['🤲','🕋'],premium:false},
{o:'eid',t:'نماز و روزه‌ات قبول 🤲',m:'در این عید فرخنده، برایت سلامتی و سعادت می‌خواهم.',s:'همیشه به یادت 🌟',ph:'photos/p026.jpg',mode:'bg',st:['⭐','💫'],premium:false},
{o:'eid',t:'عیدتان خجسته! 🕌',m:'هلال عید، پیام‌آور شادی است؛ مبارک!',s:'قربانت ❤️',ph:'photos/p033.jpg',mode:'frame',st:['🕋','🌙'],premium:true},
{o:'eid',t:'مبارک باد! 🌙',m:'عید، پاداش بندگی است؛ گوارایت باد.',s:'با عشق 💜',ph:'photos/p040.jpg',mode:'bg',st:['💫','🕌'],premium:false},
{o:'thanks',t:'ممنونم! 🙏',m:'از صمیم قلب سپاسگزارم؛ خوبی‌ات را فراموش نمی‌کنم.',s:'دوستدارت 🌸',ph:'photos/p047.jpg',mode:'frame',st:['🙏','✨'],premium:false},
{o:'thanks',t:'سپاسگزارم 🌿',m:'در سختی کنارم بودی؛ ممنونم.',s:'از طرف خانواده ❤️',ph:'photos/p054.jpg',mode:'bg',st:['🌿','❤️'],premium:false},
{o:'thanks',t:'لطف کردی! 🙏',m:'لطف تو را هیچ‌وقت جبران نمی‌توانم کرد.',s:'با بهترین آرزوها ✨',ph:'photos/p061.jpg',mode:'frame',st:['✨','🌸'],premium:true},
{o:'thanks',t:'قدردانم ✨',m:'تو همیشه بهترینی؛ ممنون برای همه‌چیز.',s:'ارادتمند شما 🤗',ph:'photos/p068.jpg',mode:'bg',st:['❤️','🤗'],premium:false},
{o:'thanks',t:'ممنون رفیق! 🤗',m:'کمکم کردی وقتی هیچ‌کس نبود؛ سپاس.',s:'همیشه به یادت 🌟',ph:'photos/p075.jpg',mode:'frame',st:['🌸','💐'],premium:false},
{o:'thanks',t:'از ته قلبم! ❤️',m:'مهربانی‌ات را در قلبم حک کردم.',s:'قربانت ❤️',ph:'photos/p082.jpg',mode:'bg',st:['🤗','🙏'],premium:false},
{o:'thanks',t:'تشکر ویژه! 🌸',m:'دنیا با آدم‌هایی مثل تو قشنگ است!',s:'با عشق 💜',ph:'photos/p089.jpg',mode:'frame',st:['💐','🌿'],premium:true},
{o:'getwell',t:'بهبودی کامل! 🌿',m:'آرزوی سلامتی و شفای عاجل؛ زود خوب شو!',s:'دوستدارت 🌸',ph:'photos/p096.jpg',mode:'bg',st:['🌿','🌸'],premium:false},
{o:'getwell',t:'زود خوب شو! 💪',m:'بیماری مهمان است، می‌رود؛ تو قوی بمان.',s:'از طرف خانواده ❤️',ph:'photos/p003.jpg',mode:'frame',st:['💪','✨'],premium:false},
{o:'getwell',t:'شفای عاجل 🌸',m:'همه برای سلامتی‌ات دعا می‌کنیم.',s:'با بهترین آرزوها ✨',ph:'photos/p010.jpg',mode:'bg',st:['🌸','🍵'],premium:false},
{o:'getwell',t:'قوی باش! 💪',m:'تخت بیمارستان جای تو نیست؛ زود برگرد!',s:'ارادتمند شما 🤗',ph:'photos/p017.jpg',mode:'frame',st:['✨','🤗'],premium:true},
{o:'getwell',t:'سلامتی! 🌿',m:'روحیه‌ات را حفظ کن؛ نصف درمان همین است.',s:'همیشه به یادت 🌟',ph:'photos/p024.jpg',mode:'bg',st:['🍵','☀️'],premium:false},
{o:'getwell',t:'نگران نباش! 🤗',m:'به زودی سر پا می‌شوی و می‌خندیم.',s:'قربانت ❤️',ph:'photos/p031.jpg',mode:'frame',st:['🤗','🌿'],premium:false},
{o:'getwell',t:'به زودی… ✨',m:'استراحت کن؛ کارها صبر می‌کنند!',s:'با عشق 💜',ph:'photos/p038.jpg',mode:'bg',st:['☀️','💪'],premium:false},
{o:'condolence',t:'تسلیت عرض می‌کنم 🕊️',m:'در غم شما شریکم؛ روحش شاد و یادش گرامی.',s:'دوستدارت 🌸',ph:'photos/p045.jpg',mode:'frame',st:['🕊️','🕯️'],premium:true},
{o:'condolence',t:'روحش شاد 🤍',m:'خداوند به شما صبر و به او رحمت عطا کند.',s:'از طرف خانواده ❤️',ph:'photos/p052.jpg',mode:'bg',st:['🤍','🤲'],premium:false},
{o:'condolence',t:'در غمت شریکم 🕊️',m:'هیچ واژه‌ای تسلای دل داغدار نیست؛ تسلیت.',s:'با بهترین آرزوها ✨',ph:'photos/p059.jpg',mode:'frame',st:['🕯️','🌿'],premium:false},
{o:'condolence',t:'خدا رحمتش کند 🤲',m:'یاد و خاطره‌اش همیشه زنده است.',s:'ارادتمند شما 🤗',ph:'photos/p066.jpg',mode:'bg',st:['🤲','✨'],premium:false},
{o:'condolence',t:'یادش گرامی 🕯️',m:'برای آرامش روحش دعا می‌کنم.',s:'همیشه به یادت 🌟',ph:'photos/p073.jpg',mode:'frame',st:['🌿','📖'],premium:true},
{o:'condolence',t:'صبر و آرامش 🤍',m:'در این روزهای سخت کنارتان هستم.',s:'قربانت ❤️',ph:'photos/p080.jpg',mode:'bg',st:['✨','🕊️'],premium:false},
{o:'condolence',t:'تسلیت 🕊️',m:'او رفت اما خوبی‌هایش ماندگار است.',s:'با عشق 💜',ph:'photos/p087.jpg',mode:'frame',st:['📖','🤍'],premium:false},
{o:'birthday',t:'سوپرایز ویژه! 🎁',m:'این کارت را نگه دار و هر وقت دلت گرفت بازش کن؛ یکی هست که دوستت دارد!',s:'رازدار تو 🤫',ph:'photos/p001.jpg',mode:'frame',st:['🎁','💜'],premium:true},
{o:'nowruz',t:'عیدی من به تو! 🧧',m:'امسال سال توست! هر روزش را جشن بگیر و از ته دل بخند.',s:'با عشق نوروزی 🌸',ph:'photos/p003.jpg',mode:'bg',st:['🧧','🌸'],premium:true},
];
